sources:
  - MomoSignature.glyphs
familyName: "Momo Signature"
cleanUp: true
extraFontmakeArgs: --filter "ufostroker::StrokeFilter(Segmentwise=True,Width=95,pre=True,StartCap='circle', EndCap='circle',JoinType='round')"
